import { Client } from '@notionhq/client';

// Initialize Notion client
const notionApiKey = process.env.NOTION_API_KEY;
const notionDatabaseId = process.env.NOTION_DATABASE_ID;

if (!notionApiKey) {
  throw new Error('NOTION_API_KEY is not defined in environment variables');
}

if (!notionDatabaseId) {
  throw new Error('NOTION_DATABASE_ID is not defined in environment variables');
}

export const notion = new Client({
  auth: notionApiKey,
});

// Allowed categories based on user's Notion database setup
// Project: Business ideas, app ideas, work projects, brainstorming
// Learning: Study, education, courses
// Personal: Private notes, diary, thoughts
// Task: To-dos, action items, reminders
const ALLOWED_CATEGORIES = [
  'Project',
  'Learning',
  'Personal',
  'Task',
] as const;

type Category = typeof ALLOWED_CATEGORIES[number];

// Category mapping for common variations and synonyms
const CATEGORY_MAPPINGS: Record<string, Category> = {
  // Exact matches
  'Project': 'Project',
  'Learning': 'Learning',
  'Personal': 'Personal',
  'Task': 'Task',
  
  // Lowercase variations
  'project': 'Project',
  'projects': 'Project',
  'learning': 'Learning',
  'personal': 'Personal',
  'task': 'Task',
  'tasks': 'Task',
  
  // Common synonyms for Project (includes business, ideas, work)
  'business': 'Project',
  'work': 'Project',
  'office': 'Project',
  'job': 'Project',
  'idea': 'Project',
  'ideas': 'Project',
  'brainstorm': 'Project',
  'app': 'Project',
  'startup': 'Project',
  
  // Learning synonyms
  'study': 'Learning',
  'education': 'Learning',
  'course': 'Learning',
  
  // Task synonyms
  'todo': 'Task',
  'to-do': 'Task',
  'action': 'Task',
  'reminder': 'Task',
  
  // Personal synonyms
  'private': 'Personal',
  'note': 'Personal',
  'notes': 'Personal',
  'diary': 'Personal',
  'thought': 'Personal',
  'thoughts': 'Personal',
};

// Category to emoji icon mapping
const CATEGORY_ICONS: Record<Category, string> = {
  'Project': '🚀',     // Rocket for projects, business, ideas
  'Learning': '📚',    // Books for learning
  'Personal': '✨',    // Sparkles for personal notes
  'Task': '✅',        // Checkmark for tasks
};

/**
 * Gets the emoji icon for a category
 */
export function getCategoryIcon(category: Category): string {
  return CATEGORY_ICONS[category] || '📝'; // Default to memo emoji
}

/**
 * Maps a category string to one of the allowed categories
 * Falls back to 'Personal' if category is unknown
 */
export function mapCategory(category: string): Category {
  // Try exact match first
  if (CATEGORY_MAPPINGS[category]) {
    return CATEGORY_MAPPINGS[category];
  }
  
  // Try case-insensitive match
  const lowerCategory = category.toLowerCase();
  if (CATEGORY_MAPPINGS[lowerCategory]) {
    return CATEGORY_MAPPINGS[lowerCategory];
  }
  
  // Fallback to Personal
  console.warn(`Unknown category "${category}", using fallback: Personal`);
  return 'Personal';
}

/**
 * Truncates text to a maximum length, preserving word boundaries
 * Handles Burmese text (Unicode) properly
 */
export function truncateSummary(text: string, maxLength: number = 200): string {
  if (!text) {
    return '';
  }
  
  // If already short enough, return as-is
  if (text.length <= maxLength) {
    return text;
  }
  
  // Truncate to maxLength
  let truncated = text.substring(0, maxLength);
  
  // Find last space to avoid cutting mid-word
  const lastSpace = truncated.lastIndexOf(' ');
  
  // Only use space boundary if it's in the last 20% of the text
  // This prevents truncating too short
  if (lastSpace > maxLength * 0.8) {
    truncated = truncated.substring(0, lastSpace);
  }
  
  return truncated.trim() + '...';
}

/**
 * Validates that the Notion database exists and is accessible
 */
export async function validateDatabase(): Promise<boolean> {
  try {
    await notion.databases.retrieve({
      database_id: notionDatabaseId!,
    });
    return true;
  } catch (error) {
    console.error('Failed to validate Notion database:', error);
    return false;
  }
}

/**
 * Data structure for creating a voice note page
 */
export interface VoiceNoteData {
  title: string;
  summary: string;
  content: string;
  category: string;
  tags: string[];
}

/**
 * Result structure returned after creating a page
 */
export interface CreatePageResult {
  success: boolean;
  pageId?: string;
  pageUrl?: string;
  error?: string;
  categoryMapped?: string;
}

/**
 * Creates a voice note page in Notion with properties and body content
 * 
 * @param data - Voice note data (generated by Gemini AI in real usage)
 * @returns Result with page ID, URL, and status
 */
export async function createVoiceNotePage(
  data: VoiceNoteData
): Promise<CreatePageResult> {
  try {
    // Validate and map category
    const mappedCategory = mapCategory(data.category);
    
    // Get category icon
    const categoryIcon = getCategoryIcon(mappedCategory);
    
    // Truncate summary to 200 characters
    const truncatedSummary = truncateSummary(data.summary, 200);
    
    // Create the page with properties and content
    const response = await notion.pages.create({
      parent: {
        database_id: notionDatabaseId!,
      },
      // Set page icon based on category
      icon: {
        type: 'emoji',
        emoji: categoryIcon,
      },
      properties: {
        // Title property - try common names
        Name: {
          title: [
            {
              text: {
                content: data.title,
              },
            },
          ],
        },
        // Summary property (text)
        Summary: {
          rich_text: [
            {
              text: {
                content: truncatedSummary,
              },
            },
          ],
        },
        // Category property (select)
        Category: {
          select: {
            name: mappedCategory,
          },
        },
        // Tags property (multi-select)
        Tags: {
          multi_select: data.tags.map((tag) => ({
            name: tag,
          })),
        },
      },
      // Page body content (full transcription)
      children: [
        {
          object: 'block',
          type: 'paragraph',
          paragraph: {
            rich_text: [
              {
                type: 'text',
                text: {
                  content: data.content,
                },
              },
            ],
          },
        },
      ],
    });

    // Extract page URL and ID from response
    const pageId = response.id;
    // Notion pages follow this URL pattern
    const pageUrl = `https://notion.so/${pageId.replace(/-/g, '')}`;

    return {
      success: true,
      pageId,
      pageUrl,
      categoryMapped: mappedCategory,
    };
  } catch (error) {
    console.error('Failed to create Notion page:', error);
    
    let errorMessage = 'Unknown error occurred';
    if (error instanceof Error) {
      errorMessage = error.message;
    }
    
    return {
      success: false,
      error: errorMessage,
    };
  }
}
